### ISSUE TITLE
Accessing MCAssoc vars from any page 

### ISSUE THREAD

**Issue by Incrementing** [lol768/XenForo-MCASSOC#16]
Is there anyway to check if a user has their minecraft profile linked?
I'm trying to make pop display to the user if they don't have an account linked.

I've tried the following IF statement but nothing...
```
<xen:if is="{$mcNames.{$user.user_id}}==null">
  send message asking user to link account.
</xen:if>
```

**Comment by lol768** [comment]
Hi there,

For performance reasons, the mcNames variable isn't added for every single action since it would require a lot of data to be transferred from the database. Right now it's only there for thread-related pages.

This isn't a bad idea though and would probably be achieved best with a `xen:helper` function since you could then query one user at a time which would be a simple `SELECT COUNT()` query which should be pretty fast.

I'll try and look at adding something like this for you.

Cheers.

**Comment by Incrementing** [comment]
Thanks, I'll see what I can do on my own using xen:helper and SQL queries.
