### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ghost** [lol768/XenForo-MCASSOC#3]
Show the username in a private conversation

**Comment by PunKeel** [comment]
Hi,

When you reply to a PM, the "dynamically added block" (with your sent message) does not include the Minecraft part.
Hadn't time to try myself to fix it, but I report here meanwhile

**Comment by lol768** [comment]
@PunKeel

I'm aware of this one since it's something I have looked into without much luck in the past. This should also probably apply to messages made in threads too. I'll have another look at some point in the future but since XenForo doesn't do much in the way of developer documentation I find writing addons for it difficult.

**Comment by lol768** [comment]
Created an issue for the above problem over at #7. Thanks for the feedback :smile:
